{% set name = "erlab" %}
{% set version = "3.15.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/erlab-{{ version }}.tar.gz
  sha256: 3115212e67767ea2f4e920f8ce38cf1a78ae4f9d273b3328c73fd4d4fd23a2a6

build:
  entry_points:
    - itool-manager = erlab.interactive.imagetool.manager:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.8.13
    - pip
  run:
    - python >={{ python_min }}
    - findiff >=0.12.0
    - h5netcdf >=1.7.1
    - igor2 >=0.5.12
    - igorwriter >=0.6.1
    - joblib >=1.3.2
    - lazy-loader >=0.4
    - lmfit >=1.3.2
    - matplotlib-base >=3.8.0
    - numba >=0.61.0
    - numexpr >=2.11.0
    - numpy >=1.26.0
    - packaging >=24.0
    - pickleshare >=0.7.5
    - pydantic >=2.11.7
    - pyperclip >=1.8.2
    - pyqtgraph >=0.13.1
    - pyzmq >=27.0.2
    - qtawesome >=1.3.1
    - qtconsole-base >=5.6.0
    - qtpy >=2.4.1
    - scipy >=1.15.0
    - tqdm >=4.66.2
    - varname >=0.13.0
    - xarray >=2024.10.0
    - xarray-lmfit >=0.3.0
  run_constrained:
    - hvplot >=0.11.0,!=0.12.0
    - astropy >=5.1.1
    - python-libarchive-c >=5.2
    - nexusformat >=1.0.6
    - numbagg >=0.8.1
    - xxhash >=3.5.0
    - iminuit >=2.25.2
    - dask >=2024.4.1
test:
  imports:
    - erlab
    - erlab.utils
    - erlab.analysis
    - erlab.io
    - erlab.plotting
    - erlab.interactive
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pyside6
    - pip

about:
  home: https://github.com/kmnhan/erlabpy
  summary: Python package for ARPES data analysis and visualization.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://erlabpy.readthedocs.io/
  dev_url: https://github.com/kmnhan/erlabpy

extra:
  recipe-maintainers:
    - kmnhan
  feedstock-name: erlabpy
