{% set name = "erlab" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erlab-{{ version }}.tar.gz
  sha256: a2daea03b7d02f6f0de45c168e2c9784281e54d80b4ca1f6c295cf878a9c1203

build:
  entry_points:
    - itool-manager = erlab.interactive.imagetool.manager:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=61
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.11
    - h5netcdf >=1.2.0
    - igor2 >=0.5.6
    - joblib >=1.3.2
    - lmfit >=1.3.2
    - matplotlib-base >=3.8.0
    - numba >=0.59.0
    - numpy >=1.26.0
    - pyperclip >=1.8.2
    - pyqtgraph >=0.13.1
    - qtawesome >=1.3.1
    - qtpy >=2.4.1
    - scipy >=1.13.0
    - tqdm >=4.66.2
    - varname >=0.13.0
    - xarray >=2024.07.0
  run_constrained:
    - astropy >=5.1.1
    - nexusformat >=1.0.6
    - numbagg >=0.8.1
    - iminuit >=2.25.2
    - dask >=2024.4.1
    - pyqt >=5.15
    - pyside2 >=5.15
    - pyside6 <6.8.0
test:
  imports:
    - erlab
    - erlab.analysis
    - erlab.io
    - erlab.plotting
    - erlab.interactive
  commands:
    - pip check
  requires:
    - pyqt >=5.15
    - pip

about:
  home: https://github.com/kmnhan/erlabpy
  summary: Python package for ARPES data analysis and visualization.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://erlabpy.readthedocs.io/
  dev_url: https://github.com/kmnhan/erlabpy

extra:
  recipe-maintainers:
    - kmnhan
  feedstock-name: erlabpy
