{% set name = "erlab" %}
{% set version = "3.11.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/erlab-{{ version }}.tar.gz
  sha256: e086b721cd8579672d7d1212117729c40e6a48674a50776a4f8fb7c1ffc0c2e0

build:
  entry_points:
    - itool-manager = erlab.interactive.imagetool.manager:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.27.0
    - pip
  run:
    - python >={{ python_min }}
    - findiff >=0.12.0
    - h5netcdf >=1.2.0
    - igor2 >=0.5.12
    - joblib >=1.3.2
    - lazy-loader >=0.4
    - lmfit >=1.3.2
    - matplotlib-base >=3.8.0
    - numba >=0.61.0
    - numpy >=1.26.0
    - pickleshare >=0.7.5
    - pyperclip >=1.8.2
    - pyqtgraph >=0.13.1
    - qtawesome >=1.3.1
    - qtconsole-base >=5.6.0
    - qtpy >=2.4.1
    - scipy >=1.15.0
    - tqdm >=4.66.2
    - varname >=0.13.0
    - xarray >=2024.10.0
    - xarray-lmfit >=0.2.1
  run_constrained:
    - astropy >=5.1.1
    - python-libarchive-c >=5.2
    - nexusformat >=1.0.6
    - numbagg >=0.8.1
    - iminuit >=2.25.2
    - dask >=2024.4.1
    - pyqt >=5.15
    - pyside2 >=5.15
test:
  imports:
    - erlab
    - erlab.utils
    - erlab.analysis
    - erlab.io
    - erlab.plotting
    - erlab.interactive
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pyqt >=5.15
    - pip

about:
  home: https://github.com/kmnhan/erlabpy
  summary: Python package for ARPES data analysis and visualization.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://erlabpy.readthedocs.io/
  dev_url: https://github.com/kmnhan/erlabpy

extra:
  recipe-maintainers:
    - kmnhan
  feedstock-name: erlabpy
